CREATE DATABASE IF NOT EXISTS home_med_chest;
USE home_med_chest;

CREATE TABLE IF NOT EXISTS storages
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name VARCHAR(50) NOT NULL,
PRIMARY KEY(id))
ENGINE InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS pharma_forms
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name VARCHAR(50) NOT NULL,
PRIMARY KEY(id))
ENGINE InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS medicine
(id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name VARCHAR(100) NOT NULL,
form_id TINYINT UNSIGNED NOT NULL,
expiration_date DATE NOT NULL,
picture_name VARCHAR(100),
storage_id TINYINT UNSIGNED NOT NULL,
comments VARCHAR(300),
PRIMARY KEY(id),
FOREIGN KEY (form_id) REFERENCES pharma_forms(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (storage_id) REFERENCES storages(id)
ON DELETE RESTRICT ON UPDATE CASCADE)
ENGINE InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS destinations
(id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name VARCHAR(100) NOT NULL,
PRIMARY KEY(id))
ENGINE InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS medicine_destinations
(medicine_id MEDIUMINT UNSIGNED NOT NULL,
destination_id SMALLINT UNSIGNED NOT NULL,
PRIMARY KEY(medicine_id, destination_id),
FOREIGN KEY (medicine_id) REFERENCES medicine(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (destination_id) REFERENCES destinations(id)
ON DELETE RESTRICT ON UPDATE CASCADE)
ENGINE InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS users
(id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name VARCHAR(20) NOT NULL,
PRIMARY KEY(id))
ENGINE InnoDB CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS medicine_users
(medicine_id MEDIUMINT UNSIGNED NOT NULL,
user_id TINYINT UNSIGNED NOT NULL,
PRIMARY KEY(medicine_id, user_id),
FOREIGN KEY (medicine_id) REFERENCES medicine(id)
ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE RESTRICT ON UPDATE CASCADE)
ENGINE InnoDB CHARACTER SET utf8;
